### ISSUE TITLE
color-switch.sh not working

### ISSUE THREAD

**Issue by NovayaFinch** [adi1090x/polybar-themes#15]
So after trying out theme 4 I realised that the color-switch.sh script is not working. I tried clicking the feather and after looking a bit into the config files and running it manually it still didnt do anything. 
I do have rofi installed.

**Comment by b-fg** [comment]
I have the same issue.

**Comment by OldNero** [comment]
@NovayaFinch @b-fg 
My polybar config was in $HOME/.config/polybar and it was lacking processions to edit the .config file to match the new color scheme, after a week I realized the fix is simple:
`sudo chmod -R 777 $HOME/.config/polybar`
basically going nuclear and recursively setting full permissions to all files in the polybar folder.
