### ISSUE TITLE
Dropping unmatched character

### ISSUE THREAD

**Issue by berensn** [adi1090x/polybar-themes#81]
Installed Polybar-5 and am getting the Dropping unmatched character message. Both fonts for the theme are installed
![Screenshot from 2020-11-16 22-27-35](https://user-images.githubusercontent.com/7515745/99342947-f6efa400-285a-11eb-80da-59a249ae0eae.png)
![Screenshot from 2020-11-16 22-24-09](https://user-images.githubusercontent.com/7515745/99342731-82b50080-285a-11eb-93c4-177692019e77.png)
![Screenshot from 2020-11-16 22-25-58](https://user-images.githubusercontent.com/7515745/99342858-c3ad1500-285a-11eb-972d-2b625f9bfb08.png)
![Screenshot from 2020-11-16 22-26-16](https://user-images.githubusercontent.com/7515745/99342865-c7d93280-285a-11eb-838d-0db43ec77f1a.png)
I tried changing out characters where there were specific icons in the config file but I still got the message

**Comment by tinseldev** [comment]
Check that the ~ /.local/share/fonts directory exists.

**Comment by sethboyles** [comment]
I believe the issue is that Polybar-5 needs Iosevka Nerd Font, not just Iosevka.

The readme just indicates that only Iosevka is necessary, but https://github.com/adi1090x/polybar-themes/blob/master/polybar-5/config.ini#L143 uses Nerd Fonts

I had the same issue, and after installing the iosevka-nerd-font package from AUR the warning disappeared and the angular glyphs showed up (although they still don't look right)

**Comment by tiny-train** [comment]
@sethboyles I think I found a fix to the angular glyphs looking weird. I love this theme, and I have had strangeness with the glyphs since day one. I was pouring over the files last night, and found that adding a space after the glyphs at the end of the user_modules.ini file fixed it for me. 

Like so:
[module/left-end-top]
inherit = module/decor-glyph
content = "%{T3} %{T-}"
- Adding a space after each one of the icons/glyphs

I hope this can help someone.

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
